//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextFinder.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class TextFinderSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static TextFinderSettings defaultInstance = ((TextFinderSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TextFinderSettings())));
        
        public static TextFinderSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath {
            get {
                return ((string)(this["FilePath"]));
            }
            set {
                this["FilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchText {
            get {
                return ((string)(this["SearchText"]));
            }
            set {
                this["SearchText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcludeFiles {
            get {
                return ((string)(this["ExcludeFiles"]));
            }
            set {
                this["ExcludeFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IncludeFiles {
            get {
                return ((string)(this["IncludeFiles"]));
            }
            set {
                this["IncludeFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchTextMatchCase {
            get {
                return ((bool)(this["SearchTextMatchCase"]));
            }
            set {
                this["SearchTextMatchCase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime CreatedAfterDate {
            get {
                return ((global::System.DateTime)(this["CreatedAfterDate"]));
            }
            set {
                this["CreatedAfterDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime CreatedBeforeDate {
            get {
                return ((global::System.DateTime)(this["CreatedBeforeDate"]));
            }
            set {
                this["CreatedBeforeDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastAccessedAfterDate {
            get {
                return ((global::System.DateTime)(this["LastAccessedAfterDate"]));
            }
            set {
                this["LastAccessedAfterDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastAccessedBeforeDate {
            get {
                return ((global::System.DateTime)(this["LastAccessedBeforeDate"]));
            }
            set {
                this["LastAccessedBeforeDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime ModifiedAfterDate {
            get {
                return ((global::System.DateTime)(this["ModifiedAfterDate"]));
            }
            set {
                this["ModifiedAfterDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime ModifiedBeforeDate {
            get {
                return ((global::System.DateTime)(this["ModifiedBeforeDate"]));
            }
            set {
                this["ModifiedBeforeDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MatchSearchTextCase {
            get {
                return ((bool)(this["MatchSearchTextCase"]));
            }
            set {
                this["MatchSearchTextCase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchSubdirectories {
            get {
                return ((bool)(this["SearchSubdirectories"]));
            }
            set {
                this["SearchSubdirectories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckNumberOfLinesBetweenSearchTextEntries {
            get {
                return ((bool)(this["CheckNumberOfLinesBetweenSearchTextEntries"]));
            }
            set {
                this["CheckNumberOfLinesBetweenSearchTextEntries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LinesBetweenSearchText {
            get {
                return ((int)(this["LinesBetweenSearchText"]));
            }
            set {
                this["LinesBetweenSearchText"] = value;
            }
        }
    }
}
